platform :ios, '11.0'

target "ElectricBusinessPlatform" do

pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Texture'
pod 'SDWebImage'
pod 'UMCCommon'
pod 'UMCSecurityPlugins'
pod 'UMCAnalytics'
pod 'UMCSecurityPlugins'
pod 'UMCShare/Social/ReducedWeChat'
pod 'UMCShare/Social/ReducedQQ'
pod 'UMCShare/Social/ReducedSina'
pod 'JPush'
pod 'SVProgressHUD'
pod 'WechatOpenSDK', '1.8.4'
pod 'pop'
pod 'AlipaySDK-iOS'
pod 'YYWebImage'
pod 'AliyunOSSiOS'
pod 'JPFPSStatus'
pod 'YBAttributeTextTapAction'
pod 'AvoidCrash'
pod 'ZLPhotoBrowser'
pod 'NIMKit/Full','2.12.7'
pod 'CocoaLumberjack'
pod 'FMDB'
pod 'SSZipArchive'
pod 'Reachability'
pod 'SDWebImageFLPlugin', '~> 0.3.0'
pod 'Bugly'
pod 'Masonry'
pod 'SJVideoPlayer'
pod 'SJUIKit'
pod 'RealReachability'
pod 'YYKeyboardManager'
pod 'YYText'
pod 'YYModel'
pod 'JXPagingView/Pager'
pod 'JXCategoryView'
pod 'GKNavigationBarViewController'
pod 'GKPageScrollView'
pod 'lottie-ios_Oc'
pod 'TXLiteAVSDK_Professional', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_Professional.podspec'
pod 'MLeaksFinder'

end

