//
//  CommonImg.h
//  CAMELLIAE
//
//  Created by 张越 on 16/3/17.
//  Copyright © 2016年 张越. All rights reserved.
//

#ifndef CommonImg_h
#define CommonImg_h


#define HomePageSelectImg             @"icon_live_red.png"
#define HomePageNoSelectImg           @"icon_live_gray.png"
#define VideoPageSelectImg            @"icon_video_red.png"
#define VideoPageNoSelectImg          @"icon_video_gray.png"
#define TypePageSelectImg             @"icon_shop_red.png"
#define TypePageNoSelectImg           @"icon_shop_gray.png"
#define ShopCarSelectImg              @"toolbar-icon-cart-fill.png"
#define ShopCarNoSelectImg            @"toolbar-icon-cart.png"
#define PersonalSelectImg             @"icon_my_red.png"
#define PersonalNoSelectImg           @"icon_my_gray.png"
#define CommunityNoSelectImg          @"icon_social_gray.png"
#define CommunitySelectImg            @"icon_social_red.png"

#define TypeSiftOfComprehensiveNoSelectImg    @"分类筛选-综合-未选中"
#define TypeSiftOfComprehensiveSelectImg    @"分类筛选-综合-选中"
#define TypeSiftComprehensiveDownSelectImg  @"原始-分类筛选-综合-下拉选中"
#define TypeSiftPriceDownSelectImg    @"分类筛选-价格-降序"
#define TypeSiftPriceUpSelectImg    @"分类筛选-价格-升序"
#define TypeSiftPriceNoSelectImg    @"分类筛选-价格-未选择.png"
#define BackBtnImg                  @"返回_白底 2.png"
#define ShopCarSelectCellImg        @"购物车-选中-cell.png"
#define ShopCarNoSelectCellImg      @"购物车-默认-未选中.png"
#define ShopCarInvalidCellImg       @"购物车-失效.png"
#define ShopCarCannotSelectCellImg  @"编组 2.png"
#define ProductShareImg             @"导航-分享.png"
#define ProductMessageShowImg       @"商品详情-选择查看.png"
#define ProductCheckShopCarImg      @"购物车-未选中-iOS.png"
#define AddShopCarSuccessImg        @"详情-购物车-加入商品.png"
#define AddShopCarNormalImg         @"详情-购物车-加入商品备份.png"
#define ProductCustomerImg          @"客服-iOS.png"
#define ProductAddNumImg            @"商品详情-数量-加-可点击.png"
#define ProductNoReduceNumImg       @"商品详情-数量-减-不可点击.png"
#define ProductReduceNumImg         @"商品详情-数量-减-可点击.png"
#define ProductNoAddNumImg          @"商品详情-数量-加-不可点击.png"
#define AddressDeleteImg            @"地址管理-删除.png"
#define CloseImg                    @"商品详情-弹窗-关闭.png"
#define WhiteBackImg                @"返回-白色-iOS.png"
#define APPServeImg                 @"首页-平台服务.png"
#define ProductDetailNoAddressImg   @"详情页配送地址.png"

#define PersonalNoPayImg                @"我的-订单-待付款.png"
#define PersonalNoDispatchImg           @"我的-订单-待发货.png"
#define PersonalDispatchImg             @"我的-订单-已发货.png"
#define PersonalFinishedImg             @"我的-订单-待评价.png"
#define PersonalDayPlayImg               @"我的-每日玩.png"
#define PersonalDayChangeImg              @"我的-每日换.png"
#define PersonalDayBackImg               @"我的-每日退.png"
#define PersonalDayLookImg               @"我的-每日看.png"
#define PersonalDayListenImg              @"我的-每日听.png"
#define PersonalAddressManageImg          @"我的-地址管理.png"
#define PersonalGroupListImg             @"我的-直拼.png"
#define PersonaladviceImg                @"我的-意见反馈.png"
#define PersonalSettingImg               @"我的-设置.png"
#define PersonalServeCenterImg            @"我的-客服中心.png"
#define PersonalVIPRecordImg              @"我的会员礼包.png"
#define PersonalInviteFriendImg           @"我的-我的好友.png"
#define VIPBuySuccessImg                 @"购买成功-头部装饰.png"
#define PersonalEnterImg                 @"箭头.png"
#define ShopCarEditImg                   @"编辑.png"
#define SHopCarFinishedImg               @"编辑备份 2.png"
#define ZFBPayImg                        @"提交订单-收银台-支付宝.png"
#define WXPayImg                         @"提交订单-收银台-微信.png"
#define SHopCarNoGoods                   @"空购物车.png"
#define PaySuccessImg                    @"支付-成功.png"
#define PayErrorImg                      @"支付-失败.png"
#define NoAddressImg                     @"无地址.png"
#define ChangeUserMessageImg             @"个人中心-个人资料修改指引.png"

#define NoVIPImg                         @"我的-会员图标-普通用户.png"
#define Lv2VIPImg                        @"我的-会员图标-银猩.png"
#define Lv3VIPImg                        @"我的-会员图标-金猩.png"
#define Lv4VIPImg                        @"我的-会员图标-红猩.png"
#define NewVIPImg                        @"我的-会员.png"
#define VIPMemberImg                     @"猩球会员-图标.png"

#define NewVIPEnterBoultImg              @"我的-会员-箭头.png"



#define BuyVIPPromImg                    @"非会员-查看权益.png"

#define CheckVIP1RightsImg               @"银星VIP-查看权益.png"
#define CheckVIP2RightsImg               @"金星VIP-查看权益.png"
#define CheckVIP3RightsImg               @"红星VIP-查看权益.png"
#define InviteUserBtnBgImg               @"按钮-渐变背景.png"


#define I5                               @"iOS-640＊1136-启动页.png"
#define I7                               @"iOS-750＊1334-启动页.png"
#define IXR                              @"iOS-1125＊2436-启动页.png"
#define IXM                              @"iOS-1242＊2688-启动页.png"
#define IXS                              @"iOS-828＊1792-启动页.png"

#define PriceLvlOneImg                   @"首页推荐-图标-银猩.png"

#define DetailPriceLvlOneImg              @"详情-图标-银猩.png"

#define PriceLvlTwoImg                   @"首页推荐-图标-红猩.png"

#define DetailPriceLvlTwoImg              @"详情-图标-红猩.png"

                                           
#define CheckAllENterImg                 @"列表-查看全部.png"

#define Lv2CardImg                       @"会员-红猩.png"
#define Lv2BuydImg                       @"会员-红猩-按钮.png"
#define LV2MesImg                        @"会员-权益-红猩.png"


#define Lv1CardImg                       @"会员-银猩.png"
#define Lv1BuydImg                       @"会员-银猩-按钮.png"
#define LV1MesImg                        @"会员-权益-银猩.png"
#define VIPMesBgImg                      @"会员-背景.png"
#define Lv2DetailMesImg                  @"红猩.png"
#define Lv1DetailMesImg                  @"银猩.png"
#define VIPDetailMesCloseImg             @"会员-弹窗-关闭.png"
#define OrderStateNoDispatchImg          @"订单详情-待发货.png"
#define OrderStateDispatchImg            @"订单详情-已发货.png"
#define OrderStateFinishedImg            @"订单详情-已完成.png"
#define OrderCloseImg                    @"订单详情-交易失败.png"
#define FirstSellProductImg              @"第一名.png"
#define SecondSellProductImg              @"第二名.png"
#define ThirdSellProductImg              @"第三名.png"
#define WHiteServeBtnImg                 @"客服-Android-白色.png"
#define BlackServeBtnImg                 @"客服-Android-黑色.png"
#define OrderDetailDisPatchImg           @"订单详情-状态-运输中.png"
#define OrderDetaillAddressImg           @"订单详情-状态-地址.png"
#define OrderDetailFinishedImg           @"订单详情-状态-签收.png"
#define NewCreateAddressImg              @"newCreate.png"

#define WXLoginImg                    @"微信.png"
#define WXTouchImg                    @"微信-点击.png"
#define SecrectShowImg                @"登录注册-密码-显示.png"
#define SecrectHidenImg               @"登录注册-密码-隐藏.png"
#define CommentPicDeleImg             @"评价晒单-删除照片.png"
#define CommentLvlNoSelectImg         @"评价晒单-星级-未选中.png"
#define CommentLvlSelectImg           @"评价晒单-星级-选中.png"
#define DetailCommentLvlSelectImg     @"评价详情-星级-选中.png"
#define DetailCommentLvlNoSelectImg   @"评价详情-星级-未选中.png"
#define DetailCommentShowAllImg       @"评论详情-展开.png"
#define DetailCommentCloseImg         @"评论详情-收起.png"
#define SearchDelegateHistoryImg      @"历史记录删除icon.png"
#define SearchBtnImg                  @"搜索.png"
#define CommentDetailLvlThreeLvl      @"评论详情-红猩.png"
#define CommentDetailLvlTwoLvl        @"评论详情-银猩.png"
#define NoCommentDataImg              @"评论-空白.png"
#define HotSearchImg                  @"热门标签内火icon.png"
#define SearchNoDataImg               @"未搜索到状态插画.png"
#define HomeVCSearchImg               @"首页搜索.png"
#define HomeVCSearch2Img              @"首页搜索2.png"
#define LiveSearchImg                 @"首页_导航_搜索.png" 
#define CloseNavAdImg                 @"关闭.png"
#define NoOrderImg                    @"无订单.png"
#define NetworkErrorImg               @"缺省页-网络出错.png"
#define NetworkSeverErrorImg          @"缺省页-服务器宕机.png"
#define NoNeedCommentList             @"待评价-列表为空.png"
#define HomePageYourLikeImg           @"首页列表-猜你喜欢.png"
#define VIPBackGroundImg              @"背景.png"
#define VIPRightsImage                @"会员权益标题.png"
#define NormalRightsImage             @"普通权益标示.png"
#define VIPTopHuImge                  @"弧形.png"
#define SaveCopyBgImg                 @"节省计算器.png"
#define SaveCopyEnterImg              @"计算器入口图标.png"
#define UserIDCopyImg                 @"会员-复制.png"
#define UserIDNewCopyImg              @"会员中心-复制按钮-白色.png"
#define UserVIPBgImage1Img            @"背景-1.png"
#define UserVIPRulesEnterImg          @"会员协议 2.png"
#define VIPGiftCheckImg               @"点击查看.png"
#define AllRightsMesTopImg            @"路径 3.png"
#define IntrouduceImg                 @"平台介绍.png"
#define IntrouduceBtnImg              @"平台介绍btn.png"
#define VIPActivityEnterBtnImg        @"会员活动入口.png"
#define NoCheckImg                    @"椭圆形1.png"
#define readyCheckImg                 @"椭圆形.png"

#define GiftRedImg                    @"礼包列表-红猩.png"
#define GiftGoldImg                   @"礼包列表-金猩.png"
#define GiftYinImg                    @"礼包列表-银猩.png"
#define GiftListPromImg               @"礼包列表-按钮.png"
#define ComplateImg                   @"完成-白色-ios.png"
#define rewardBtnImg                  @"确认订单-消费奖励说明.ong"
#define deductionOffImg               @"红包抵扣开关-关闭.png"
#define deductionOnImg                @"红包抵扣开关-开启.png"
#define alterRewardImg                @"确认订单-修改红包抵扣金额.png"
#define alterDisallowAddImg           @"确认订单-修改红包金额-加-不可点击.png"
#define alterAllowAddimg              @"确认订单-修改红包金额-加-可点击.png"
#define alterDisallowReduceImg        @"确认订单-修改红包金额-减-不可点击.png"
#define alterAllowReduceImg           @"确认订单-修改红包金额-减-可点击.png"

#define NewPricelvl4Img               @"价格-VIP会员价-红猩.png"
#define NewPricelvl3Img               @"价格-VIP会员价-金猩.png"
#define NewPricelvl2Img               @"价格-VIP会员价-银猩.png"

#define NewVIPPromlvl4Img             @"VIP会员价-红猩标识.png"
#define NewVIPPromlvl3Img             @"VIP会员价-金猩标识.png"
#define NewVIPPromlvl2Img             @"VIP会员价-银猩标识.png"

#define NotiPromRedPointImg           @"提示圆点.png"
#define NotiRedPacketImg              @"消息-红包消息.png"
#define NotiLogisticsImg              @"消息-交易物流.png"
#define NotiSystemImg                 @"消息-消息通知.png"

#define RedPacketBuyerImg             @"购物送红包-购买者.png"
#define RedPacketRecommenderImg       @"购物送红包-推荐者.png"

#define ActivateVIPImg                @"激活.png"
#define OldUserBuyImg                 @"老用户购买.png"
#define RedPacketShortRulesImg        @"红包说明-弹窗.png"
#define DetailProductRedPacketImg     @"详情页-购物送红包-说明.png"
#define RedPacketDetailRulesImg       @"红包说明-跳转页面.png"
#define ShareQzoneImg                 @"live_popover_share_moments.png"
#define ShareUserImg                  @"live_popover_share_wechat.png"
#define ShareQQUserImg                @"live_popover_share_qq.png"
#define ShareQQzoneImg                @"live_popover_share_qzone.png"
#define ShareWeiboImg                 @"live_popover_share_sina.png"
#define ShareReportImg                @"live_more_report.png"
#define PersonalInvaiteImg            @"我的-邀请参会.png"
#define MyNotiEnterImg                @"我的-消息.png"
#define NoNotiImg                     @"消息-交易物流-空.png"

#define BuyLvl2SuccessImg             @"购买成功-银猩.png"
#define BuyLvl3SuccessImg             @"购买成功-金猩.png"
#define BuyLvl4SuccessImg             @"购买成功-红猩.png"

#define lvl4BgImageImg                @"红猩new.png"
#define lvl3BgImageImg                @"金猩new.png"
#define lvl2BgImageImg                @"银猩new.png"
#define lvl1BgImageImg                @"普通new.png"
#define VIPCenterLvl1IconImg          @"会员文字图标-普通用户.png"
#define VIPCenterLvl2IconImg          @"会员文字图标-银猩.png"
#define VIPCenterLvl3IconImg          @"会员文字图标-金猩.png"
#define VIPCenterLvl4IconImg          @"会员文字图标-红猩.png"
#define NewTypeAssistImg              @"一级分类-选中圆角-ios.png"
#define BannerBgImage                 @"banner背景.png"
#define BannerBgStoreImage            @"背景-商城.png"
#define BannerBgExaminationImage      @"背景-体检.png"
#define BannerBgBeautifyImage         @"背景-美容.png"
#define BannerBgPlasticImage          @"背景-整形.png"
#define BannerBgTypeImage             @"首页-通用分类.png"
#define BannerBgTypeGrayImage         @"首页-通用分类-白底.png"

#define BannerBg2Image                @"双12 首页入口切图.png"
#define JinGangFoodImg                @"三少美食.png"
#define JinGangWorldImg               @"三少全球.png"
#define JinGangOldImg                 @"老字号.png"
#define JinGangRedPacketImg           @"猩球红包.png"
#define SancellAdImg                  @"三少头条-标题.png"
#define HomePageAllShowSearchImg      @"首页-导航栏-搜索icon.png"
#define HomePageNotiPromWhiteImg      @"首页-导航栏-消息-iOS-白色.png"
#define HomePageNotiPromBlackImg      @"首页-导航栏-消息-iOS-黑色.png"
#define SpeedKillbgImg                @"限时秒杀-背景.png"
#define SpeedKillTitleImg             @"限时秒杀-标题.png"
#define BannerSelectImg               @"banner-切换-选中.png"
#define BannerUnSelectImg             @"banner-切换-未选中.png"
#define InvoiceReadingImg             @"开发票-发票须知.png"
#define InvoiceKnowImg                @"发票须知.png"
#define InvaiteFirendbgImg            @"邀请好友背景图.png"
#define InvaiteFirendJoinBtnImg       @"邀请好友参会btn.png"
#define SpeedKillTopBgImg             @"秒杀头部背景图.png"
#define SpeedKillTopTitleImg          @"限时秒杀.png"
#define SpeedKillClockImg             @"秒杀列表-提醒我-iOS.png"
#define SpeedKillClockedImg           @"秒杀列表-提醒我-已提醒-iOS.png"
#define DetailProductTopBgImg         @"详情-限时秒杀-背景-安卓.png"
#define DetailProductTopBg2Img        @"双十二活动背景.png"
#define DetailProductWillKillPromImg  @"详情-限时秒杀-秒杀预告标识.png"
#define DetailProductKillIngPromImg   @"详情-限时秒杀-标识.png"
#define SpeedKillBtnBgImg             @"详情-按钮-活动色.png"
#define ActivityBtnBg2Img             @"双十二btn.png"
#define YourLikeSpeedKillPromImg      @"显示秒杀标识-购物车.png"
#define VIPSpeedKillBtnImg            @"button-秒杀.png"
#define SpeedKillTopicPromImg         @"限时秒杀-引导按钮.png"
#define ProductDetailKillMesBgImg     @"详情-限时秒杀-背景.png"

#define CurrentAppLogoImg             @"Logo.png"
#define HomePageModuleLogoImg         @"默认加载-大.png"
#define otherImagePlaceholderImg      @"默认加载-小.png"
#define Lvl2BuyBtnImg                 @"银猩购买按钮.png"
#define Lvl3BuyBtnImg                 @"金猩购买按钮.png"
#define Lvl4BuyBtnImg                 @"红猩购买按钮.png"
#define HomePageKillBtnImg            @"HomePageKillBtn.png"
#define NewSpeedToKillBtnImg          @"秒杀列表-马上抢-iOS.png"
#define NewSpeedKilTopBgImg           @"秒杀列表头部-背景.png"
#define NewVipModuleSpeedKillBtnImg   @"vipSpeedKillBtn.png"
#define WebVIPRightTopImg             @"权益详情-背景-原生.png"
#define NewVIPRightsPromImg           @"猩球会员-专属VIP权益.png"
#define HomePageMoreImg               @"Home查看更多.png"
#define InvaiteFirendbannerImg        @"App-邀请好友-banner.png"
#define InvaiteStyleImg               @"邀请方式.png"
#define InvaiteProgressImg            @"邀请流程.png"
#define DetailLvlOneVIPMesImg         @"详情页-会员图标-普通用户"
#define DetailLvlFourVIPMesImg        @"详情页-会员图标-红猩.png"
#define DetailLvlThreeVIPMesImg       @"详情页-会员图标-金猩.png"
#define DetailLvlTwoVIPMesImg         @"详情页-会员图标-银猩.png"
#define NoInviteFirendImg             @"noInviateFriend.png"
#define CommunityMessageImg           @"社群消息.png"
#define CommunityCreateGroupImg       @"社群创建群组.png"
#define CommunitySearchGroupImg       @"社群查找群组.png"
#define CommunityMailListImg          @"社群通讯录.png"
#define MailListSearchGroupImg        @"通讯录查找新群组.png"
#define MailListCreateGroupImg        @"通讯录创建群组.png"
#define MailListGroupMessageImg       @"通讯录验证消息.png"
#define CloseVideoImg                 @"视频-关闭.png"
#define SHarePosterBgImg              @"分享海报.png"
#define ProductJudgeAreaPromImg       @"检测配送地址.png"
#define ProductAllServePromImg        @"商品全部服务标示.png"

#define ProductGroupBgImg             @"直拼价格背景.png"
#define ProductGroupPromImg           @"直拼标示.png"
#define ProductGroupBg2Img            @"直拼群组背景色2.png"
#define CreateOrderGroupPromImg       @"直拼订单页面标示.png"
#define GroupProgressImg              @"直拼流程.png"
#define GroupProgressPromImg          @"直拼流程标示.png"
#define GroupProgressRulePromImg      @"直拼规则标示.png"
#define GroupingPersonBgImg           @"拼团人.png"
#define GroupingPerson2BgImg          @"拼团多人.png"

#define LiveListCouponsIcon           @"icon_coupon_list.png"
#define LiveCouponsListCloseIcon      @"icon_close_live_ popover.png"
#define LiveCouponsShowIcon           @"icon_coupon_live.png"
#define LivePlayExitIcon              @"icon_exit_live.png"
#define LiveCouponsShowImage          @"image_coupon_live_list.png"

#define VouchersListCellBgImg         @"image_coupon_list_usable.png"
#define VouchersListCellBg2Img        @"image_coupon_bg_list_usable_explain.png"

#define Inline static inline
#pragma mark --设置添加图片

Inline NSString * CommentAddPicImg(int index){
    
    if (index == 0) {
      
        return @"添加照片-默认.png";
    }else{
     
        return [NSString stringWithFormat:@"添加照片-默认-%d.png",index];
    }
}

Inline NSString * HotSellImg(int index){
        
    return [NSString stringWithFormat:@"热销排行-标识-%d.png",index];

}

#endif /* CommonImg_h */
